print ("print degani bu masalan print deb yozib keyin kovus chiqazib qosh tirnokn koyib ichiga narslar yozish mumkin agar son ozix qosh tirnok shartmas")
print("py degan bu pythonniki deyiladi ")
print ("fail bu ichiga faqat narsa qod yozish mumkin uyerga papka jolashtirib bolmaydi")
print ("papka bu ichiga faqat fail papkalar oyin va boshkalar qoyish mumkin ")
print ("python bu biz ishlavotgan prlojena biz uyerda faqat qod yozish mumkin")